const hard = ["Accurate", "Banana", "Computer", "Dinosaur", "Elephant", "Furniture", "Galaxy", "Hippopotamus",
    "Illustrate", "Jubilant", "Kaleidoscope", "Labyrinth", "Microscope", "Neighborhood", "Octagonal",
    "Parliament", "Questionnaire", "Rhinoceros", "Spectacular", "Thermostat", "Unanimous", "Vacuum",
    "Wanderlust", "Xylophone", "Yellowish", "Zucchini", "Accessibility", "Biodegradable", "Congregation",
    "Diversification", "Enthusiastic", "Flabbergasted", "Geographical", "Humanitarian", "Impersonation",
    "Jurisdiction", "Kilometer", "Linguistic", "Metropolitan", "Negotiation", "Ornamental", "Philosophical",
    "Quantitative", "Reciprocal", "Sophisticated", "Technological", "Underestimated", "Vulnerability",
    "Watershed", "Extravagant", "Youthfulness", "Zoological", "Anthropology", "Bureaucracy", "Circumference",
    "Discombobulate", "Existential", "Fibonacci", "Gravitational", "Homogeneous", "Iconoclast", "Juxtapose",
    "Kaleidoscopic", "Logarithmic", "Monochromatic", "Nomenclature", "Onomatopoeia", "Prognosticate",
    "Quintessential", "Rambunctious", "Stereotype", "Trigonometry", "Unprecedented", "Vertigo", "Whimsical",
    "Exponential", "Yttrium", "Zephyr", "Accommodate", "Belligerent", "Catastrophic", "Differential",
    "Eccentric", "Facetious", "Gregarious", "Harmonious", "Inconsequential", "Jurisprudence", "Kinetoscope",
    "Luminescent", "Misanthrope", "Nonchalant", "Oxymoron", "Photosynthesis", "Quarantine", "Rendezvous",
    "Synonymous", "Translucent", "Ubiquitous", "Vicarious", "Whistleblower", "Extrapolate", "Yield", "Zenith",
    "Supercalifragilisticexpialidocious", "NASA", "FBI", "CIA", "USA", "NATO", "UNICEF", "EU", "HTML", "UFO",
    "ASAP", "ATM", "BBC",
    "CEO", "CFO", "COP", "COVID", "CPU", "DIY", "DMV", "DNA", "DOA", "EOD", "ESPN", "FOMO",
    "FYI", "GPS", "HDMI", "HIV", "IBM", "ICU", "ID", "IRS", "JPEG", "LCD", "LED", "LGBT",
    "LOL", "MBTI", "MIA", "MVP", "NBA", "NFL", "NSA", "PDF", "PPE", "PSA", "PTO", "RAM",
    "RGB", "RSVP", "SAT", "SUV", "TBA", "TBD", "TSA", "USB", "VIP", "VR", "WHO", "WIFI", "WWF", "CAPTCHA"
];